/**
 * ⚠️ WARNING / ATENCIÓN — CRITICAL PRODUCTION SERVER FILE ⚠️
 * DO NOT MODIFY THIS FILE OR CHANGE ITS IMPORT PATHS / EXTENSIONS.
 * ANY CHANGES TO THIS FILE BY AI AGENTS OR AI STUDIO MUST BE PREVENTED
 * TO AVOID BREAKING THE VERCEL SERVERLESS RUNTIME (ERR_MODULE_NOT_FOUND).
 * IMPORTS MUST RETAIN THE ".js" EXTENSION.
 */

import app from "../server.js";

export default app;
